# Generated by Django 5.1.3 on 2024-12-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('header', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(default='')),
                ('tag', models.CharField(default='', max_length=122)),
                ('eventdate', models.IntegerField(default=1)),
                ('eventday', models.TextField(default='')),
                ('eventmonth', models.TextField(default='')),
                ('eventyear', models.IntegerField(default=2020)),
                ('organizer', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='CCI', editable=False, max_length=100)),
                ('concentration', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.URLField(blank=True, default='/static/img/logo-new.png', help_text="URL to the user's profile picture", null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='home.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
