# Generated by Django 5.1.3 on 2024-11-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_contact_id_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(default='CCI', editable=False, max_length=100),
        ),
    ]
