# Generated by Django 5.1.3 on 2024-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_profile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='home.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, default='https://example.com/default_profile_picture.jpg', help_text="URL to the user's profile picture", null=True),
        ),
    ]
