# Generated by Django 5.1.3 on 2024-12-10 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile_following_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='eventpage',
            name='concentrations',
            field=models.ManyToManyField(related_name='events', to='home.concentration'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='concentration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.concentration'),
        ),
        migrations.CreateModel(
            name='UserEventInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('register', 'Register')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='home.eventpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'interaction_type')},
            },
        ),
    ]
