# Generated by Django 5.1.3 on 2024-12-10 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile_following_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rsvped_events',
            field=models.ManyToManyField(blank=True, related_name='rsvp_profiles', to='home.event'),
        ),
    ]
