# Generated by Django 5.1.3 on 2024-12-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_profile_followers_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, default='/static/img/logo-new.png', help_text="URL to the user's profile picture", null=True),
        ),
    ]
