# Generated by Django 5.1.3 on 2024-12-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_concentration_eventpage_concentrations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='concentration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='concentrations',
        ),
        migrations.AlterUniqueTogether(
            name='usereventinteraction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usereventinteraction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='usereventinteraction',
            name='user',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='matched_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='similarity_scores',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(default='CCI', editable=False, max_length=225),
        ),
        migrations.DeleteModel(
            name='Concentration',
        ),
        migrations.DeleteModel(
            name='UserEventInteraction',
        ),
    ]
