# Generated by Django 5.1.3 on 2024-12-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_event_profile_rsvped_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rsvped_events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
