# Generated by Django 5.1.3 on 2024-12-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_concentration_alter_profile_concentration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='desc',
            new_name='description',
        ),
    ]
